# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\m3u8downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("m3u8下载")
        Form.resize(641, 375)
        Form.setWindowIcon(QtGui.QIcon('favicon.ico'))
        
        self.groupBox1 = QtWidgets.QGroupBox(Form)
        self.groupBox1.setGeometry(QtCore.QRect(20, 15, 601, 181))
        self.groupBox1.setObjectName("groupBox1")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)

        self.inputUrlsEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.inputUrlsEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.inputUrlsEdit.setObjectName("inputUrlsEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputUrlsEdit)

        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.saveDirEdit = QLineEditWidget(self.formLayoutWidget)
        self.saveDirEdit.setObjectName("saveDirEdit")
        self.saveDirEdit.mousePress.connect(self.onSelectDir)
        self.saveDirEdit.setReadOnly(True)

        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.saveDirEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.outputFormatComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.outputFormatComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.outputFormatComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outputFormatComboBox.setObjectName("outputFormatComboBox")
        self.outputFormatComboBox.addItem("a")
        self.outputFormatComboBox.addItem("b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.outputFormatComboBox)

        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 210, 601, 131))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 581, 100))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")

        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setEnabled(True)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)

        self.fileNameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fileNameLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileNameLabel)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileNameLabel)

        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.progressLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.progressLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.progressLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.progressLabel.setObjectName("progressLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progressLabel)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.progressBar = QtWidgets.QProgressBar(self.formLayoutWidget_2)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.progressBar)

        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.stateLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.stateLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.stateLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stateLabel.setObjectName("stateLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stateLabel)

        self.startDownloadBtn = QtWidgets.QPushButton(Form)
        self.startDownloadBtn.setGeometry(QtCore.QRect(420, 345, 100, 23))
        self.startDownloadBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startDownloadBtn.setObjectName("start download")
        self.startDownloadBtn.clicked.connect(Form.onStartClick)

        self.stopDownloadBtn = QtWidgets.QPushButton(Form)
        self.stopDownloadBtn.setGeometry(QtCore.QRect(530, 345, 100, 23))
        self.stopDownloadBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stopDownloadBtn.setObjectName("stop download")
        self.stopDownloadBtn.clicked.connect(Form.onStopClick)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "M3U8 Downloader"))
        self.groupBox1.setTitle(_translate("Form", "基础配置"))
        self.label.setText(_translate("Form", "URL："))
        self.label_2.setText(_translate("Form", "保存目录："))
        self.label_3.setText(_translate("Form", "文件格式："))
        self.outputFormatComboBox.setItemText(0, _translate("Form", "MP4"))
        self.outputFormatComboBox.setItemText(1, _translate("Form", "FLV"))
        self.startDownloadBtn.setText(_translate("Form", "开始下载"))
        self.stopDownloadBtn.setText(_translate("Form", "停止下载"))
        self.stopDownloadBtn.setEnabled(False)
        self.groupBox.setTitle(_translate("Form", "正在下载"))
        self.label_4.setText(_translate("Form", "文件名称："))
        self.fileNameLabel.setText(_translate("Form", "没有正在下载的视频"))
        self.label_6.setText(_translate("Form", "下载进度："))
        self.progressLabel.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "分片进度："))
        self.label_9.setText(_translate("Form", "当前状态："))
        self.stateLabel.setText(_translate("Form", self.lang['downState']['ready']))
    # 选择文件夹
    def onSelectDir(self):
        save_dir = QtWidgets.QFileDialog.getExistingDirectory(self, "选取文件夹") 
        if save_dir:
            self.saveDirEdit.setText(save_dir)
        self.saveDirEdit.clearFocus()

    # 窗口居中
    def center(self):
      qr = self.frameGeometry()
      cp = QtWidgets.QDesktopWidget().availableGeometry().center()
      qr.moveCenter(cp)
      self.move(qr.topLeft())

    def formData(self):
        self.form = {}
        self.form['urls'] = self.getUrls()
        self.form['save_path'] = self.saveDirEdit.text()
        self.form['output_format'] = self.outputFormat()
        print(self.form)
        return self.form

    def outputFormat(self):
        return self.outputFormatComboBox.currentText()

    def getUrls(self):
        inputUrlStr = self.inputUrlsEdit.toPlainText().replace('\n','')
        if inputUrlStr:
            return inputUrlStr.split(";")
        else:
            return []
    @property
    def fileName(self):
      return self.fileNameLabel.text()
      

class QLineEditWidget(QtWidgets.QLineEdit):
    mousePress = QtCore.pyqtSignal()

    def mousePressEvent(self, event):
        self.mousePress.emit()
        super().mousePressEvent(event)

    def focusOutEvent(self, event):
        super().focusOutEvent(event)